RECIPES = [
    {
        "name": "Veggie Omelet",
        "meal_type": "breakfast",
        "dietary_preference": "vegetarian",
        "ingredients": ["eggs", "spinach", "tomato", "cheese"],
        "description": "A quick omelet packed with spinach, tomato, and cheese.",
        "prep_time": "15 min",
        "difficulty": "Easy",
        "tags": ["quick", "savory", "protein"],
        "ratings": [4, 5],
        "average_rating": 4.5,
    },
    {
        "name": "Berry Oat Bowl",
        "meal_type": "breakfast",
        "dietary_preference": "vegan",
        "ingredients": ["oats", "blueberries", "banana", "almond milk"],
        "description": "Creamy oats with fruit for a fast plant-based breakfast.",
        "prep_time": "10 min",
        "difficulty": "Easy",
        "tags": ["sweet", "fiber", "make-ahead"],
        "ratings": [4, 4, 5],
        "average_rating": 4.33,
    },
    {
        "name": "Avocado Toast",
        "meal_type": "breakfast",
        "dietary_preference": "vegan",
        "ingredients": ["bread", "avocado", "lemon", "pepper"],
        "description": "Toasted bread topped with seasoned avocado.",
        "prep_time": "8 min",
        "difficulty": "Easy",
        "tags": ["quick", "fresh"],
        "ratings": [3, 4, 5],
        "average_rating": 4.0,
    },
    {
        "name": "Chicken Rice Bowl",
        "meal_type": "lunch",
        "dietary_preference": "high-protein",
        "ingredients": ["chicken", "rice", "broccoli", "soy sauce"],
        "description": "A simple lunch bowl with chicken, rice, and broccoli.",
        "prep_time": "25 min",
        "difficulty": "Easy",
        "tags": ["meal-prep", "protein"],
        "ratings": [5, 4],
        "average_rating": 4.5,
    },
    {
        "name": "Black Bean Taco Bowl",
        "meal_type": "lunch",
        "dietary_preference": "vegan",
        "ingredients": ["black beans", "rice", "corn", "avocado", "salsa"],
        "description": "A filling taco bowl with beans, rice, corn, and salsa.",
        "prep_time": "20 min",
        "difficulty": "Easy",
        "tags": ["budget", "fiber", "meal-prep"],
        "ratings": [5, 5, 4],
        "average_rating": 4.67,
    },
    {
        "name": "Turkey Lettuce Wraps",
        "meal_type": "lunch",
        "dietary_preference": "gluten-free",
        "ingredients": ["turkey", "lettuce", "carrot", "cucumber", "soy sauce"],
        "description": "Crunchy lettuce wraps with seasoned turkey and vegetables.",
        "prep_time": "18 min",
        "difficulty": "Easy",
        "tags": ["light", "protein", "low-carb"],
        "ratings": [4, 4],
        "average_rating": 4.0,
    },
    {
        "name": "Tofu Stir Fry",
        "meal_type": "dinner",
        "dietary_preference": "vegan",
        "ingredients": ["tofu", "broccoli", "carrot", "soy sauce"],
        "description": "A savory stir fry with tofu and fresh vegetables.",
        "prep_time": "25 min",
        "difficulty": "Medium",
        "tags": ["one-pan", "plant-protein"],
        "ratings": [4],
        "average_rating": 4.0,
    },
    {
        "name": "Pasta Primavera",
        "meal_type": "dinner",
        "dietary_preference": "vegetarian",
        "ingredients": ["pasta", "tomato", "zucchini", "garlic"],
        "description": "A vegetable pasta dish with tomato and zucchini.",
        "prep_time": "30 min",
        "difficulty": "Medium",
        "tags": ["comfort", "vegetables"],
        "ratings": [5],
        "average_rating": 5.0,
    },
    {
        "name": "Salmon Quinoa Plate",
        "meal_type": "dinner",
        "dietary_preference": "gluten-free",
        "ingredients": ["salmon", "quinoa", "spinach", "lemon"],
        "description": "A balanced dinner with salmon, quinoa, greens, and lemon.",
        "prep_time": "35 min",
        "difficulty": "Medium",
        "tags": ["balanced", "omega-3"],
        "ratings": [5, 4, 5],
        "average_rating": 4.67,
    },
    {
        "name": "Chickpea Curry",
        "meal_type": "dinner",
        "dietary_preference": "vegan",
        "ingredients": ["chickpeas", "tomato", "spinach", "coconut milk", "rice"],
        "description": "A warm curry with chickpeas, tomato, spinach, and rice.",
        "prep_time": "35 min",
        "difficulty": "Medium",
        "tags": ["comfort", "plant-protein"],
        "ratings": [4, 5, 5],
        "average_rating": 4.67,
    },
]
