RECIPES = [
    {
        "name": "Veggie Omelet",
        "meal_type": "breakfast",
        "dietary_preference": "vegetarian",
        "ingredients": ["eggs", "spinach", "tomato", "cheese"],
        "description": "A quick omelet packed with spinach, tomato, and cheese.",
        "ratings": [4, 5],
        "average_rating": 4.5,
    },
    {
        "name": "Chicken Rice Bowl",
        "meal_type": "lunch",
        "dietary_preference": "high-protein",
        "ingredients": ["chicken", "rice", "broccoli", "soy sauce"],
        "description": "A simple lunch bowl with chicken, rice, and broccoli.",
        "ratings": [5, 4],
        "average_rating": 4.5,
    },
    {
        "name": "Tofu Stir Fry",
        "meal_type": "dinner",
        "dietary_preference": "vegan",
        "ingredients": ["tofu", "broccoli", "carrot", "soy sauce"],
        "description": "A savory stir fry with tofu and fresh vegetables.",
        "ratings": [4],
        "average_rating": 4.0,
    },
    {
        "name": "Avocado Toast",
        "meal_type": "breakfast",
        "dietary_preference": "vegan",
        "ingredients": ["bread", "avocado", "lemon", "pepper"],
        "description": "Toasted bread topped with seasoned avocado.",
        "ratings": [3, 4, 5],
        "average_rating": 4.0,
    },
    {
        "name": "Pasta Primavera",
        "meal_type": "dinner",
        "dietary_preference": "vegetarian",
        "ingredients": ["pasta", "tomato", "zucchini", "garlic"],
        "description": "A vegetable pasta dish with tomato and zucchini.",
        "ratings": [5],
        "average_rating": 5.0,
    },
]
